Repository jbaublitz/getset, pull requests merged in 2025-01, with the labels that each got.

#98 Unary tuple struct getter/setter
  src/generate.rs
  src/lib.rs
  tests/unary_tuple.rs
Labels: enhancement

#101 Fix clippy errors
  src/generate.rs
Labels: maintenance

#100 CI updates
  .github/workflows/test.yml
Labels: ci

#102 Add 'WithSetters' proc_macro_derive
  Cargo.toml
  README.md
  examples/simple.rs
  src/generate.rs
  src/lib.rs
  tests/skip.rs
  tests/unary_tuple.rs
  tests/with_setters.rs
Labels: enhancement

#104 v0.1.4
  Cargo.toml
Labels: release
