Repository jbaublitz/getset, pull requests merged in 2025-06, with the labels that each got.

#112 Add `CloneGetters`
  src/generate.rs
  src/lib.rs
  tests/clone_getters.rs
Labels: enhancement

#116 Update README to mention CloneGetters
  README.md
  examples/simple.rs
Labels: documentation

#118 Update in-code docs to mention CloneGetters
  src/lib.rs
Labels: documentation

#121 Bump release to v0.1.6
  Cargo.toml
Labels: release

#122 Update Rust edition
  Cargo.toml
  src/generate.rs
  src/lib.rs
Labels: maintenance
